name: Build library and test via googletest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build library
      run: make

  test:

    runs-on: ubuntu-latest

    steps:
    - name: install googletest
      run: sudo apt install googletest
    - uses: actions/checkout@v3
    - name: build and run tests
      run: make test
