name: codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codecov:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: install googletest
      run: sudo apt-get -y install googletest
    - name: generate coverage
      run: make -C test coverage-run
    - name: upload coverage to codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
