name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: install googletest
      run: sudo apt-get -y install googletest
    - uses: actions/checkout@v4
    - name: build and run tests
      run: make test
    - name: build and run tests with custom crc implementation
      run: make -C test test-with-custom-crc
