name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: install googletest
      run: sudo apt-get -y install googletest
    - uses: actions/checkout@v3
    - name: build and run tests
      run: make test
